config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/auth/:provider/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  get '/followers', to: 'followers#index', as: :followers
  get '/followers/:follower', to: 'followers#show', as: :follower_activities 
  get '/following', to: 'followings#index', as: :following
  get '/starred', to: 'starred#index', as: :starred
  get '/recent_activities', to: 'recent_activities#index', as: :recent_activities
  get '/organizations', to: 'organizations#index', as: :organizations
  get '/repos', to: 'repos#index', as: :repos
end

app/models/activity.rb
class Activity
  attr_reader :repo, :type, :commit_messages, :time, :url

  def initialize(activity_info)
    @repo = activity_info[:repo][:name]
    @type = activity_info[:type]
    @url = activity_info[:repo][:url]
    @commit_messages = format_commits(activity_info)
    @time = DateTime.parse(activity_info[:created_at])
  end

  def format_commits(activity)
    number = 0
    activity[:payload][:commits].map do |commit|
      "#{number += 1}. #{commit[:message]}"
    end.join("\n")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commit.rb
class Commit
  attr_reader :url, :repo, :commit_message, :time

  def initialize(commit_info)
    @url = commit_info[:url]
    @repo = commit_info[:repository][:name]
    @time = DateTime.parse(commit_info[:commit][:author][:date])
    @commit_message = commit_info[:commit][:message]
  end
end

app/models/follower.rb
class Follower
  attr_reader :username, :image

  def initialize(follower_info)
    @username = follower_info[:login]
    @image = follower_info[:avatar_url]
  end
end

app/models/organization.rb
class Organization
  attr_reader :name, :image, :description

  def initialize(org_info)
    @name = org_info[:login]
    @image = org_info[:avatar_url]
    @description = org_info[:description]
  end
end

app/models/repo.rb
class Repo
  attr_reader :name, :owner, :url, :date_created, :most_recently_updated
  
  def initialize(repo_info)
    @name = repo_info[:name]
    @owner = repo_info[:owner][:login]
    @url = repo_info[:url]
    @date_created = Date.parse(repo_info[:created_at])
    @most_recently_updated = Date.parse(repo_info[:updated_at])
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.create_with_omniauth(auth)
    create(provider: auth[:provider],
          uid: auth[:uid],
          name: auth[:info][:name],
          token: auth[:credentials][:token],
          image: auth[:extra][:raw_info][:avatar_url],
          username: auth[:extra][:raw_info][:login])
  end
end

app/models/user_search.rb
class UserSearch
  attr_reader :service

  def initialize(user)
    @service ||= GithubUserService.new(user)
  end

  def starred_repos
    @service.call_starred_repos.map do |star|
      Repo.new(star)
    end
  end

  def user_repos
    @service.call_user_repos.map do |repo|
      Repo.new(repo)
    end
  end

  def return_followers
    @service.call_followers.map do |follower|
      Follower.new(follower)
    end
  end

  def return_followings
    @service.call_followings.map do |follower|
      Follower.new(follower)
    end
  end

  def return_user_activities
    @service.call_user_activities.map do |activity|
      Activity.new(activity) if activity[:payload][:commits].present?
    end.compact
  end

  def return_user_organizations
    if @service.call_user_organizations.empty? == false
      @service.call_user_organizations.map do |org|
        Organization.new(org)
      end
    else
      "This user is not currently involved with any organizations"
    end
  end

  def followings_activities(following_username)
    following_activities = @service.call_following_activities(following_username).pop(5).sort_by { |commit| commit[:commit][:author][:date] }.reverse
    following_activities.map { |activity| Commit.new(activity) }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    followers = UserSearch.new(current_user)
    @github_followers = followers.return_followers
  end

  def show
    follower = UserSearch.new(current_user)
    @github_follower = follower.followings_activities(params[:follower])
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def index
    @github_followings = UserSearch.new(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    orgs = UserSearch.new(current_user)
    @user_organizations = orgs.return_user_organizations
    
  end
end

app/controllers/recent_activities_controller.rb
class RecentActivitiesController < ApplicationController
  def index
    recent = UserSearch.new(current_user)
    @user_recent_activities = recent.return_user_activities
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    repos = UserSearch.new(current_user)
    @user_repos = repos.user_repos
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    user.update(token: auth["credentials"]["token"])
    session[:user_id] = user.id
    redirect_to '/'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/starred_controller.rb
class StarredController < ApplicationController
  def index
    starred = UserSearch.new(current_user)
    @starred_repos = starred.starred_repos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/followers/index.html.erb
<h2>Followers</h2>
<% @github_followers.each do |follower| %>
<div class="follower">
  <p class="username"><%= follower.username %></p>
  <img src="<%= follower.image %>"><br>
  <%= link_to "#{follower.username}'s recent activities", follower_activities_path(follower.username) %><br><br>
</div>
<% end %>

app/views/followers/show.html.erb
<% @github_follower.each do |commit| %>
  Repo Affected: <%= commit.repo %><br>
  Link to Commit: <a href="<%= commit.url %>"><%= commit.url %></a><br>
  Time: <%= commit.time.strftime("%Y.%m.%d at %I:%M%p") %><br>
  Commit Message: <%= commit.commit_message %><br><br>
<% end %>

app/views/followings/index.html.erb
<h1> <%= current_user.name %> is currently following: </h1>
<% @github_followings.return_followings.each do |following| %>
<div class="following">
  <h2 class="username"><%= following.username %></h2><br>
  <img src="<%= following.image %>" alt="prof_pic"><br>
  <h4><%= following.username %>'s recent commits</h4>
</div>
  <% @github_followings.followings_activities(following.username).each do |commit| %>
    Repo Affected: <%= commit.repo %><br>
    Link to Commit: <a href="<%= commit.url %>"><%= commit.url %></a><br>
    Time: <%= commit.time.strftime("%Y.%m.%d at %I:%M%p") %><br>
    Commit Message**: <%= commit.commit_message %><br><br>
  <% end %>
<% end %>

app/views/home/index.html.erb
<% if current_user %>
Welcome <%= current_user.name %><br>
<img src="<%= current_user.image %>"><br>
<%= link_to 'followers', followers_path %><br>
<%= link_to 'following', following_path %><br>
<%= link_to 'starred repos', starred_path %><br>
<%= link_to 'your repos', repos_path %><br>
<%= link_to 'your organizations', organizations_path %><br>
<%= link_to 'your recent activity', recent_activities_path %><br>
<%= link_to "Logout", '/logout' %>
<% else %>
<%= link_to "Login to Github", "/auth/github" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apicurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/organizations/index.html.erb
<%= current_user.name %>'s Organizations: <br><br><br>
  <% @user_organizations.each do |organization| %>
    Name: <%= organization.name %><br>
    <img src="<%= organization.image %>" alt=""><br>
    Description: <%= organization.description %><br><br>
  <% end %>

app/views/recent_activities/index.html.erb
<%= current_user.name %>'s Recent Activity: <br><br><br>
<% @user_recent_activities.each do |activity| %>
  Repo Affected: <a href="<%= activity.url %>"><%= activity.repo %></a><br>
  Event Type: <%= activity.type %><br>
  Commit Message**: <%= activity.commit_messages %><br>
  When: <%=activity.time.strftime("%Y.%m.%d at %I:%M%p") %><br><br>
<% end %>

app/views/repos/index.html.erb
<%= current_user.name %>'s Repos <br><br><br>

<% @user_repos.each do |repo| %>
  Name: <%= repo.name %><br>
  Owner: <%= repo.owner %><br>
  <a href="<%= repo.url %>">See Repo</a><br>
  Date Created: <%= repo.date_created.strftime('%Y.%m.%d') %><br>
  Date Most Recently Updated: <%= repo.most_recently_updated.strftime('%Y.%m.%d') %><br><br><br>
<% end %>

app/views/starred/index.html.erb
<h1>Total Starred Repos for <%= current_user.name %>: <%= @starred_repos.count %></h2>

<% @starred_repos.each do |repo| %>
Name: <%= repo.name %><br>
Owner: <%= repo.owner %><br>
<a href="<%= repo.url %>">See Repo</a><br>
Date Created: <%= repo.date_created.strftime('%Y.%m.%d') %><br>
Date Most Recently Updated: <%= repo.most_recently_updated.strftime('%Y.%m.%d') %><br><br><br>
<% end %>